return {
}
-- return {
--   'akinsho/bufferline.nvim',
--   version = "*",
--   event = "VeryLazy",
--   keys = {
--     { "<leader>tp", "<Cmd>BufferLineTogglePin<CR>",            desc = "Toggle pin" },
--     { "<leader>tP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete non-pinned buffers" },
--     { "<leader>to", "<Cmd>BufferLineCloseOthers<CR>",          desc = "Delete other buffers" },
--     { "<leader>tr", "<Cmd>BufferLineCloseRight<CR>",           desc = "Delete buffers to the right" },
--     { "<leader>tl", "<Cmd>BufferLineCloseLeft<CR>",            desc = "Delete buffers to the left" },
--     { "<S-h>",      "<cmd>BufferLineCyclePrev<cr>",            desc = "Prev buffer" },
--     { "<S-l>",      "<cmd>BufferLineCycleNext<cr>",            desc = "Next buffer" },
--   },
--   dependencies = { 'nvim-tree/nvim-web-devicons' },
--   config = function()
--     local bufferline = require('bufferline')
--     bufferline.setup {
--       options = {
--         mode = "tabs",
--         separator_style = "slant",
--         diagnostics = "nvim_lsp",
--         diagnostics_indicator = function(count, _, _, _)
--           return "(" .. count .. ")"
--         end,
--         groups = {
--           items = {
--             require('bufferline.groups').builtin.pinned:with({ icon = "" })
--           }
--         },
--         offsets = {
--           {
--             filetype = "NvimTree",
--             text = function()
--               return vim.fn.fnamemodify(vim.fn.getcwd(), ":t")
--             end,
--             separator = true
--           }
--         },
--       }
--     }
--   end,
-- }
